### ISSUE TITLE
Replace underscore dependencies with amp dependencies

### ISSUE THREAD

**Issue by gonsfx** [AmpersandJS/ampersand-collection-underscore-mixin#12]
Or maybe just create an `ampersand-collection-amp-mixin` :+1:

**Comment by ben-eb** [comment]
+1, although now Lo-Dash has been bumped to `3.x` it might be better to use it instead.

**Comment by gonsfx** [comment]
i'm fine with underscore, lodash or amp-modules. as long as everything handlebars-related uses the same.

whats the deal with lo-dash `3.x` - why would you rather use that?

**Comment by ben-eb** [comment]
@gonsfx lo-dash `3.x` solves much of the large dependency graph that was one of the motivating factors to create amp modules. It has definitely been made a much more modular library now.

**Comment by ahdinosaur** [comment]
if there's interest in moving to lodash, i (re-)wrote a [lodash 2.x mixin](https:/github.com/ahdinosaur/ampersand-collection-lodash-mixin) that might be a useful start.

**Comment by wraithgar** [comment]
I would say that this lib can stay as-is, seeing as how it's explicitly the underscore mixin.  A lodash mixin can always be written, and switched to in places we want to default to that.

**Comment by gonsfx** [comment]
To sum this up, everyone who uses `ampersand-rest-collection` in his ampersand app is punished by having both underscore and a shitload of lodash modules in his resulting javascript bundle.

Really!?

Imho, all `ampersand-*` modules should be rewritten to only use `lodash` modules. No `underscore`, no `amp-*` and no `object-extend`. Filesize matters, after all.

Especially modules that i would consider as core such as `ampersand-rest-collection` should adhere to this self-imposed rule, deprecating the use of this one and requiring an `ampersand-lodash-mixin`.

**Comment by klaemo** [comment]
Checkout https://github.com/klaemo/ampersand-collection-lodash-mixin
Looks silly, but might be the way to go forward.
I replaced all the methods except `.chain`, which I couldn't figure out how to do.

**Comment by lukekarrys** [comment]
I agree with @wraithgar that this is the `underscore` mixin and should stay as-is. I'm not sure why people would want to use it, but it already exists and I don't think we should change it.

@gonsfx There is already work being done to get the `ampersand-collection-lodash-mixin` ready and replaced in `ampersand-rest-collection`. That was always the plan to have all the core modules depend on `lodash` and not `underscore` anymore. But I think this module needs to remain unchanged.

**Comment by gonsfx** [comment]
I'd still mark this as deprecated or advise against using it in the docs because of the obvious disadvantages.

**Comment by lukekarrys** [comment]
Good call @gonsfx. I've opened up #13 to handle that.
