### ISSUE TITLE
this._reset() is undefined

### ISSUE THREAD

**Issue by HipsterBrown** [AmpersandJS/ampersand-collection-underscore-mixin#7]
I was going through the Human JavaScript online videos when I encountered an error during 4-5 "Creating a collection for users". 

```
TypeError: 'undefined' is not a function (evaluating 'this._reset()')
```

This error is traced back to the Collection function within ampersand-collection.js

```
function Collection(models, options) {
  options || (options = {});
  if (options.model) this.model = options.model;
  if (options.comparator) this.comparator = options.comparator;
  if (options.parent) this.parent = options.parent;
  this._reset();
  this.initialize.apply(this, arguments);
  if (models) 
    this.reset(models, extend({
      silent: true
    }, options));
}
```

I think it may have something to do with the recent update to Underscore to 1.7.0, which apparently had some breaking changes. I tried rolling back the dependency to 1.6.0 but it is still breaking. 

Any help would be great.

**Comment by aaronmccall** [comment]
@HipsterBrown, any word on this?

**Comment by HipsterBrown** [comment]
Oh, yes. You were right in the first comment. Issue is solved.
